### ISSUE TITLE
一个页面多个网络请求 对话框展示如何优化呢

### ISSUE THREAD

**Issue by Biswangluo** [tough1985/RxjavaRetrofitDemo#11]
对话框会连续展示好几个

**Comment by tough1985** [comment]
如果是同时发起多个请求的话，推荐你用Rxjava2的zip操作符，他会等两个事件都完成之后一起返回数据给订阅者。
如果是一个请求之后接着发另一个请求，可以使用FlatMap。
最近比较忙  过一段时间准备写一个RxJava2的Demo，主要把这种嵌套问题解决掉

**Comment by DuoLa512** [comment]
大佬，你的RxJava2的demo出来了没
