### ISSUE TITLE
我封装返回值如果data不为空的时候没问题，但是data为空的时候直接Gson解析出错了

### ISSUE THREAD

**Issue by RedStartGong** [tough1985/RxjavaRetrofitDemo#7]

**Comment by RedStartGong** [comment]
`public class HttpResult<T> implements Serializable {
    private String message;
    private int code;
    private T data;
}`
`    /**
     \* numSum : 28
     \* numC : 13
     */

```
private AttendanceBean attendance;

public AttendanceBean getAttendance() {
    return attendance;
}

public void setAttendance(AttendanceBean attendance) {
    this.attendance = attendance;
}

public static class AttendanceBean {
    private int numSum;
    private int numC;

    public int getNumSum() {
        return numSum;
    }

    public void setNumSum(int numSum) {
        this.numSum = numSum;
    }

    public int getNumC() {
        return numC;
    }

    public void setNumC(int numC) {
        this.numC = numC;
    }
}
```

}`
`Observable<HttpResult<StudentEvaluation>> getStudentEva`

`public class HttpResultFunc<T> implements Func1<HttpResult<T>,T> {
    @Override
    public T call(HttpResult<T> re) {
        if (re.getCode() != 200) {
            throw new ApiException(re.getMessage());
        }
        return re.getData();
    }
}`
这是部分代码，不知道还有人出现这种问题没有，错误信息：
`com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 30 path $.data`

**Comment by tough1985** [comment]
貌似你的json封装的信息问题，data为空的时候里面是什么样的呢？data=null还是data=""？

**Comment by RedStartGong** [comment]
{"message":"该学院暂无统计","data":"","code":201} 不是null，就是“”

**Comment by RedStartGong** [comment]
如果返回数据为空，是否可以设计成{"message":"该学院暂无统计","data":{},"code":201} 或者
{"message":"该学院暂无统计","data":[],"code":201}呢
